name: Pull req Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm' 
      
      - run: npm ci
      - run: npm run lint
      - run: npm run build

       
    




